---
name: gatorgrader-sample-latex-lab
break: true
fastfail: false
indent: 4
---
src/main/latex/samplelab:
    example.tex:
        --exists
        --fragment "\section" --count 3
        --fragment "\paragraph" --count 2
        --fragment "\LaTeXe{}" --count 1
        --fragment "\bibliography{main}" --count 1
        --regex "\\begin([^;]*)\\end" --count 1

    sample.bib:
        --exists
        --fragment "@article" --count 1
        --fragment "@InProceedings" --count 1

# if you wish to specify an exact gatorgrader command... must include --json
# gg: --directory src/main/java/samplelab --file SampleLabMain.java --exists --json
