---
name: gatorgrader-samplelab
break: true
fastfail: false
indent: 4
---
src/main:
    java:
        samplelab/SampleLabMain.java:
            --exists
            --single 1 --language Java
            --multi 3 --language Java
            --fragment "println(" --count 2
            --fragment "new DataClass(" --count 1
            --fragment "new Date(" --count 2
        samplelab/DataClass.java:
            --exists
            --multi 1 --language Java
            --fragment "int " --count 1
writing/reflection.md:
    mdl
    --paragraphs 2
    --words 6
--commits 18

# if you wish to specify an exact gatorgrader command... must include --json
# gg: --directory src/main/java/samplelab --file SampleLabMain.java --exists --json
